### ISSUE TITLE
(infinite) download loop get interrupted by raised exception

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#153]
While NASA's hosting is unavailable, MODAPE download routine raises an exception and downloading (loop of retries) is interrupted. Stack trace:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f6247a64f10>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='e4ftl01.cr.usgs.gov', port=443): Max retries exceeded with url: //MODV6_Cmp_B/MOLA/MYD13A2.006/2019.10.24/MYD13A2.A2019297.h18v06.006.2019316201018.hdf.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6247a64f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/var/storage/arc_modape_chain/arc_modis_ndvi.py", line 143, in app_do_init
    do_init(app_state)
  File "/var/storage/arc_modape_chain/arc_modis_ndvi.py", line 438, in do_init
    downloads = modis_download.callback(
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/modape/scripts/modis_download.py", line 176, in cli
    downloaded = query.download(
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/modape/modis/download.py", line 315, in download
    downloaded_temp = [x.result() for x in futures]
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/modape/modis/download.py", line 315, in <listcomp>
    downloaded_temp = [x.result() for x in futures]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/modape/modis/download.py", line 228, in _fetch
    with session.get(url + ".xml") as response:
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/var/storage/virtualenv/arc-modis-ndvi/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='e4ftl01.cr.usgs.gov', port=443): Max retries exceeded with url: //MODV6_Cmp_B/MOLA/MYD13A2.006/2019.10.24/MYD13A2.A2019297.h18v06.006.2019316201018.hdf.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6247a64f10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by interob** [comment]
Looks like we should add ConnectionError to this list:
https://github.com/WFP-VAM/modape/blob/9206ad2738e904b80709322863556cd08272b02e/modape/modis/download.py#L241

**Comment by interob** [comment]
Also being thrown: NewConnectionError, urllib3.exceptions.MaxRetryError

**Comment by valpesendorfer** [comment]
fixed with #154
