### ISSUE TITLE
modis_window type cast missing for xRes and yRes parameters

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#164]
Running this command:
`python modis_window.py -b 2002-07-15 -e 2020-12-25 --clip-valid --round-int 2 \
  --roi -26.0,-35.0,58.0,38.0 --gdal-kwarg xRes=0.01 --gdal-kwarg yRes=0.01 \
  -d ./VIM/SMOOTH/EXPORT ./VIM/SMOOTH`

Gives the following exception:

```Traceback (most recent call last):
  File "modis_window.py", line 219, in <module>
    cli_wrap()
  File "modis_window.py", line 216, in cli_wrap
    cli() #pylint: disable=E1120
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "modis_window.py", line 190, in cli
    mosaic.generate_mosaics(
  File "/usr/local/lib/python3.8/dist-packages/modape/modis/window.py", line 244, in generate_mosaics
    "width": abs(int(round((aoi[2] - aoi[0]) / output_res[0]))),
TypeError: unsupported operand type(s) for /: 'float' and 'str'```

**Comment by valpesendorfer** [comment]
fixed with #169
