### ISSUE TITLE
Smoothing fails for 5th new time after initialisation

### ISSUE THREAD

**Issue by interob** [WFP-VAM/modape#58]
For testing purposes, I have a downloaded + collected + smoothed mini archive over only Dec 2018. From there, I am producing new time steps from Jan 1st 2019 onwards: 1-by-1, forcing an nsmooth/nupdate of 64/6. All works fine until the 5th time step (DOY 33) is downloaded and ingested; applying the whittaker filter makes MODAPE crash:
[2019-06-26 00:50:39]: Starting smoothMODIS.py ... 

Running whittaker smoother with s value from grid ... 

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/ARC/Documents/2019/VAM NDVI/africa_1km/scripts/africa_1km.py", line 110, in <module>
    'nsmooth': 64, 'nupdate': 6 })
  File "D:\ARC\Documents\2019\VAM NDVI\africa_1km\scripts\modis_smooth.py", line 403, in modis_smooth
    smt_h5.ws2d_sgrid()
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\modape\modis.py", line 949, in ws2d_sgrid
    smt_ds[br:br+rawchunks[0], bco:bco+rawchunks[1]] = arr_smooth[:, bc:bc+rawchunks[1]]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\h5py\_hl\dataset.py", line 707, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\h5py\_hl\selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, self.mshape))
TypeError: Can't broadcast (57600, 6) -> (57600, 5)

In order to reproduce the error, please unzip the files and install the modified modis.py
Initialization: python3 scripts/africa_1km_init.py -b 2018-12-01 -e 2018-12-31 .
Production: python3 scripts/africa_1km.py -c 2018-12-31 .
[africa_1km.zip](https://github.com/WFP-VAM/modape/files/3327691/africa_1km.zip)

**Comment by valpesendorfer** [comment]
Thanks for reporting @interob 

Please note, that an error or potential bug needs to be reproducible with the current release of `modape`, not a modified version that needs to be installed.

If you can, please detail the steps needed to arrive to your desired outcome using _unmodified_ `modape` functionality.

Thanks

**Comment by interob** [comment]
I have now setup a series of calls into unmodified modape (modis.py, v0.1.7) that reproduces the issue; please find the script in the attached ZIP.

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/ARC/Documents/2019/VAM NDVI/reproduce_consqupd/reproduce_smoothing_err.py", line 83, in <module>
    download_ingest_smooth(download_params)
  File "D:/ARC/Documents/2019/VAM NDVI/reproduce_consqupd/reproduce_smoothing_err.py", line 52, in download_ingest_smooth
    'nsmooth': 64, 'nupdate': 6})
  File "D:\ARC\Documents\2019\VAM NDVI\reproduce_consqupd\modis_smooth.py", line 403, in modis_smooth
    smt_h5.ws2d_sgrid()
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\modape\modis.py", line 938, in ws2d_sgrid
    smt_ds[br:br+rawchunks[0], bco:bco+rawchunks[1]] = arr_smooth[:, bc:bc+rawchunks[1]]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\h5py\_hl\dataset.py", line 707, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\h5py\_hl\selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, self.mshape))
TypeError: Can't broadcast (57600, 6) -> (57600, 5)


[reproduce_smoothing_err.zip](https://github.com/WFP-VAM/modape/files/3349734/reproduce_smoothing_err.zip)

**Comment by valpesendorfer** [comment]
Unfortunately I was unable to reproduce your error using the standard `modape` implementation.

After initializing the raw and the smooth HDF5 files with the data from 2018-12, I would run the following commands in succession for each of your combinations for start & end date

- start/end: 2019-01-01
- start/end: 2019-01-09
- start/end: 2019-01-17
- start/end: 2019-01-25
- start/end: 2019-02-02

```
modis_download m?d13a2 --tile-filter h21v07 h21v08 --user **** --password **** --download --aria2 -b <start_date> -e <end_date>

modis_collect /home/maintainer/ -d /home/maintainer/ --interleave

mv *hdf olddata/

modis_smooth VIM/ -d /home/maintainer/smooth -t 10

```

Here's the output of `modis_info` after the final (5th) iteration:


                                           MODAPE info tool - 2019-07-02 15:34:35


> File: smooth/MXD13A2.h21v07.006.txd.VIM.h5
> 
> Type: MODIS smoothed HDF5
> 
> Dimensions:
> 
>     - 1200 rows
> 
>     - 1200 columns
> 
>     - 8 temporal units
> 
> Start date: 2018329
> 
> End date: 2019036
> 
> Temporal resolution: 10 daily
> 
> Spatial resolution: 926.6254330558334 m
> 
> NoData value: -3000
> 
> Last modified: 2019-07-02 15:26:13
> 
> Last smoothing run: Whittaker smoother with fixed s from grid
