### ISSUE TITLE
--nworkers & --parallel-tiles

### ISSUE THREAD

**Issue by valpesendorfer** [WFP-VAM/modape#60]
Received following traceback:

> Traceback (most recent call last):
>   File "/opt/conda/bin/modis_smooth", line 11, in <module>
>     load_entry_point('modape', 'console_scripts', 'modis_smooth')()
>   File "/home/jovyan/modape/modape/scripts/modis_smooth.py", line 243, in main
>     pool = Pool(processes=args.parallel_tiles, initializer=initfun, initargs=(processing_dict,))
>   File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 175, in __init__
>     self._repopulate_pool()
>   File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 236, in _repopulate_pool
>     self._wrap_exception)
>   File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 250, in _repopulate_pool_static
>     wrap_exception)
>   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 73, in __init__
>     assert group is None, 'group argument must be None for now'

**Comment by valpesendorfer** [comment]
Seems to be an issue with daemon processes.

See [corresponding SO question](https://stackoverflow.com/questions/52948447/error-group-argument-must-be-none-for-now-in-multiprocessing-pool).

Error could not be reproduced at this stage, so issue will be monitored

**Comment by valpesendorfer** [comment]
not more applicable for V1
