### ISSUE TITLE
duplicates in collect

### ISSUE THREAD

**Issue by valpesendorfer** [WFP-VAM/modape#68]
Recently NASA has been publishing duplicate versions of some hdf files.

If there are duplicates fed into the `modis_collect` stept, it raises an `AssertionError` as planned - but also an `UnboundLocalError` which is not intended.

Needs to be investigated further and fixed so these situations are handled in a better way.

Traceback:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/modape-0.2.1-py3.6-linux-x86_64.egg/modape/scripts/modis_collect.py", line 32, in run_process
    interleave=pdict['interleave'])
  File "/opt/conda/lib/python3.6/site-packages/modape-0.2.1-py3.6-linux-x86_64.egg/modape/modis.py", line 283, in __init__
    assert len(set(self.rawdates)) == self.nfiles, "Number of files not equal to number of derived dates - are there duplicate HDF files?"
AssertionError: Number of files not equal to number of derived dates - are there duplicate HDF files?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/modis_collect", line 11, in <module>
    load_entry_point('modape==0.2.1', 'console_scripts', 'modis_collect')()
  File "/opt/conda/lib/python3.6/site-packages/modape-0.2.1-py3.6-linux-x86_64.egg/modape/scripts/modis_collect.py", line 136, in main
    run_process(processing_dict[group])
  File "/opt/conda/lib/python3.6/site-packages/modape-0.2.1-py3.6-linux-x86_64.egg/modape/scripts/modis_collect.py", line 38, in run_process
    print('\nError processing product {}, product code {}. \n\n Traceback:\n'.format(rh5.product, vam_product_code))
UnboundLocalError: local variable 'rh5' referenced before assignment
```

**Comment by valpesendorfer** [comment]
fixed with #70
