### ISSUE TITLE
Review usage of gdal V3

### ISSUE THREAD

**Issue by valpesendorfer** [WFP-VAM/modape#73]
for now gdal has a version limit to < 3.

Need to check if that can be lifted.

**Comment by valpesendorfer** [comment]
Error in `window_modis` using `gdal 3`:

```
Traceback (most recent call last):
  File "/data/work/modape/modape/scripts/modis_window.py", line 266, in main
    options=wopt,
  File "/opt/conda/lib/python3.7/site-packages/osgeo/gdal.py", line 625, in Warp
    return wrapper_GDALWarpDestName(destNameOrDestDS, srcDSTab, opts, callback, callback_data)
  File "/opt/conda/lib/python3.7/site-packages/osgeo/gdal.py", line 3410, in wrapper_GDALWarpDestName
    return _gdal.wrapper_GDALWarpDestName(*args)
TypeError: in method 'wrapper_GDALWarpDestName', argument 4 of type 'GDALWarpAppOptions *'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/modis_window", line 11, in <module>
    load_entry_point('modape', 'console_scripts', 'modis_window')()
  File "/data/work/modape/modape/scripts/modis_window.py", line 271, in main
    print('Error while reading {} data for {}! Please check if dataset exits within file. \n\n Error message:\n\n {}'.format(args.dataset, filename, e))
AttributeError: 'Namespace' object has no attribute 'dataset'
ERROR 1: PROJ: proj_as_wkt: Open of /opt/conda/share/proj failed
ERROR 1: PROJ: proj_create_from_wkt: Open of /opt/conda/share/proj failed
ERROR 1: PROJ: proj_as_wkt: Open of /opt/conda/share/proj failed
ERROR 1: PROJ: proj_create_from_name: Open of /opt/conda/share/proj failed
```

**Comment by valpesendorfer** [comment]
> Error in `window_modis` using `gdal 3`:
> 
> ```
> Traceback (most recent call last):
>   File "/data/work/modape/modape/scripts/modis_window.py", line 266, in main
>     options=wopt,
>   File "/opt/conda/lib/python3.7/site-packages/osgeo/gdal.py", line 625, in Warp
>     return wrapper_GDALWarpDestName(destNameOrDestDS, srcDSTab, opts, callback, callback_data)
>   File "/opt/conda/lib/python3.7/site-packages/osgeo/gdal.py", line 3410, in wrapper_GDALWarpDestName
>     return _gdal.wrapper_GDALWarpDestName(*args)
> TypeError: in method 'wrapper_GDALWarpDestName', argument 4 of type 'GDALWarpAppOptions *'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/bin/modis_window", line 11, in <module>
>     load_entry_point('modape', 'console_scripts', 'modis_window')()
>   File "/data/work/modape/modape/scripts/modis_window.py", line 271, in main
>     print('Error while reading {} data for {}! Please check if dataset exits within file. \n\n Error message:\n\n {}'.format(args.dataset, filename, e))
> AttributeError: 'Namespace' object has no attribute 'dataset'
> ERROR 1: PROJ: proj_as_wkt: Open of /opt/conda/share/proj failed
> ERROR 1: PROJ: proj_create_from_wkt: Open of /opt/conda/share/proj failed
> ERROR 1: PROJ: proj_as_wkt: Open of /opt/conda/share/proj failed
> ERROR 1: PROJ: proj_create_from_name: Open of /opt/conda/share/proj failed
> ```

This could be actually the bug from issue #77

**Comment by valpesendorfer** [comment]
adding gdal3 is messing with travis - will keep the restriction for now and revisit later
