### ISSUE TITLE
float in np.linspace

### ISSUE THREAD

**Issue by valpesendorfer** [WFP-VAM/modape#75]
When specifying an `srange` for smoothing, `np.linspace` now raises an exception when presented with float input:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/modape-0.4.0-py3.6-linux-x86_64.egg/modape/scripts/modis_smooth.py", line 181, in main
    abs((float(args.srange[0])-float(args.srange[1])))/float(args.srange[2]) + 1.0)
  File "<__array_function__ internals>", line 6, in linspace
  File "/usr/local/lib/python3.6/dist-packages/numpy-1.18.1-py3.6-linux-x86_64.egg/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```
Fix: change to `np.arange`?

**Comment by interob** [comment]
This bug does not affect the s-grid modape usage scenario, does it?

**Comment by valpesendorfer** [comment]
No, this only applies when using the V-curve for optimization of S. Also, using the predefined smoothing chain doesn't seem to be an issue either. It's purely when you specify a manual `--srange` in `modis_smooth`
