### ISSUE TITLE
vp bug in ws2doptvp

### ISSUE THREAD

**Issue by valpesendorfer** [WFP-VAM/modape#79]
running `modis_smooth` with `--optvp` and `--nworkers` > 1 resulted in error with traceback:

> Running whittaker smoother asymmetric V-curve optimization ... 
> 
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "/usr/local/lib/python3.6/dist-packages/modape-0.4.0-py3.6-linux-x86_64.egg/modape/utils.py", line 608, in execute_ws2d_vc
>     vprec=vp)
> UnboundLocalError: local variable 'vp' referenced before assignment
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/modis_smooth", line 11, in <module>
>     load_entry_point('modape==0.4.0', 'console_scripts', 'modis_smooth')()
>   File "/usr/local/lib/python3.6/dist-packages/modape-0.4.0-py3.6-linux-x86_64.egg/modape/scripts/modis_smooth.py", line 320, in main
>     smt_h5.ws2d_vc(args.srange, args.pvalue, constrain=args.constrain)
>   File "/usr/local/lib/python3.6/dist-packages/modape-0.4.0-py3.6-linux-x86_64.egg/modape/modis/smooth.py", line 761, in ws2d_vc
>     _ = pool.map(execute_ws2d_vc, map_index)
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
> UnboundLocalError: local variable 'vp' referenced before assignment
>

**Comment by valpesendorfer** [comment]
fixed on `develop-v0.4`
